name: Sync Dev to Other Branches

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Sync Dev to Other Branches
        run: |
          TARGETS=("qa" "frontend" "backend")

          for TARGET in "${TARGETS[@]}"; do
            git checkout $TARGET
            git pull origin $TARGET || echo "No changes to pull for $TARGET"
            git reset --hard origin/dev
            git merge --squash origin/dev || echo "No changes to merge for $TARGET"
            if [ -n "$(git status --porcelain)" ]; then
              git commit -m "Squash merge changes from dev into $TARGET"
              git push origin $TARGET || echo "Failed to push $TARGET branch"
            fi
            git reset --hard dev
            git push origin $TARGET --force || echo "Failed to force push $TARGET branch"
          done
